load("@devbase//ts:index.bzl", "ts_directory")

package(default_visibility = ["//visibility:public"])

ts_directory(
    name = "export",
    deps = [
        "//src/core",
        "//src/tag",
    ],
)
